name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Get version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Build binaries
      run: make all
    
    - name: Prepare release assets
      run: |
        cd dist
        for dir in */; do
          os=${dir%/}
          for arch_dir in $dir*/; do
            arch=${arch_dir#$dir}
            arch=${arch%/}
            binary=$(find $arch_dir -type f -executable)
            if [ -n "$binary" ]; then
              ext=""
              [ "$os" = "windows" ] && ext=".exe"
              cp "$binary" "../opml2pptx-${{ steps.version.outputs.VERSION }}-${os}-${arch}${ext}"
            fi
          done
        done
    
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: opml2pptx-*
        generate_release_notes: true